sudo: required

services:
  - docker

before_install: npm install -g npm@latest
install: npm ci

after_success:
  - sha256sum build/* > build/SHA256SUMS
  - cat build/SHA256SUMS

script: |-
  version=$(grep '"version":' src/drivers/webextension/manifest.json | sed 's/^.*"version": "\(.*\)".*$/\1/'); ./run build $version

env:
  - CXX=g++-4.8
